# This is a basic workflow to help you get started with Actions

name: merge_integration_into_prod

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: prod
          
    
      # Runs a set of commands using the runners shell
      - name: merge integration into prod
        run: |
          git config --global user.name "PROD Archives_sync"
          git config --global user.email "github_archives_sync@fenway.com"
          rm -rf *
          git add *
          git commit -m "rm all"
          git push origin prod 
      
      - name: copying integration content over 
        run: |
          git merge -m "int" --allow-unrelated-histories -X theirs origin/integration
          git add .
          git push origin prod
          

