# This is a basic workflow to help you get started with Actions

name: merge-model-changes-into-another-repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0 # number of commits to fetch, 0 = all history and tags for all branches, default = 1
#           #ref: integration #specifies branch, tag or SHA, otherwise default branch
          
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: jliwill/test-1
          
      # Runs a set of commands using the runners shell
#       - name: merge dev into integration
#         run: |
#           git config --global user.name "INTEGRATION Archives_sync"
#           git config --global user.email "github_archives_sync@fenway.com"
#           git merge -m "dev" --allow-unrelated-histories -X theirs origin/dev
#           git add .
#           git push origin integration     

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
